global:
  stackNamePrefix: sample-central-combined
  ssmPrefix: /sample-central-combined/network
  region: us-west-2
  availabilityZones:
    - us-west-2a
    - us-west-2b
  tags:
    - aws-vpc-builder: sample-central-combined

providers:
  internet:
    central-egress:
      vpcCidr: 10.1.63.192/26
      style: natEgress
      useTransit: central
  firewall:
    egress-inspection:
      vpcCidr: 100.64.0.0/16
      useTransit: central
      style: awsNetworkFirewall
      firewallDescription: sample-central-egress-tgw AWS Network Firewall
      firewallName: InspectionEgress
    ingress-inspection:
      vpcCidr: 100.64.0.0/16
      useTransit: central
      style: awsNetworkFirewall
      firewallDescription: sample-central-ingress-tgw AWS Network Firewall
      firewallName: InspectionIngress

vpcs:
  isolatedVpcOne:
    style: workloadIsolated
    vpcCidr: 10.10.0.0/19
    providerInternet: central-egress
    subnets:
      workload:
        cidrMask: 20
  isolatedVpcTwo:
    style: workloadIsolated
    vpcCidr: 10.11.0.0/19
    providerInternet: central-egress
    subnets:
      workload:
        cidrMask: 20
  centralPublic:
    style: workloadPublic
    vpcCidr: 10.12.0.0/19
    subnets:
      workload:
        cidrMask: 20
  workloadIsolated:
    style: workloadIsolated
    vpcCidr: 10.13.0.0/19
    subnets:
      workload:
        cidrMask: 20

transitGateways:
  central:
    style: transitGateway
    tgwDescription: sample-central-combined-tgw Transit Gateway
    defaultRoutes:
      - vpcName: isolatedVpcOne
        routesTo: central-egress
        inspectedBy: egress-inspection
      - vpcName: isolatedVpcTwo
        routesTo: central-egress
        inspectedBy: egress-inspection
    blackholeRoutes:
      - vpcName: isolatedVpcOne
        blackholeCidrs:
          - isolatedVpcTwo
      - vpcName: isolatedVpcTwo
        blackholeCidrs:
          - isolatedVpcOne
    dynamicRoutes:
      - vpcName: centralPublic
        routesTo: workloadIsolated
        inspectedBy: ingress-inspection
